# Chapter 00 pytorch fundamentals

In [3]:
import torch
torch.__version__

'2.0.1'

In [4]:
# Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [5]:
scalar.ndim

0

In [7]:
# Get the Python number within a tensor (only works with one-element tensors)
scalar.item()

7

In [10]:
# Default datatype for tensors is float32
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # defaults to None, which is torch.float32 or whatever datatype is passed
                               device=None, # defaults to None, which uses the default tensor type
                               requires_grad=False) # if True, operations performed on the tensor are recorded 

float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

In [11]:
float_16_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float16) # torch.half would also work

float_16_tensor.dtype

torch.float16

In [12]:
# Create a tensor
some_tensor = torch.rand(3, 4)

# Find out details about it
print(some_tensor)
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Device tensor is stored on: {some_tensor.device}") # will default to CPU

tensor([[0.4275, 0.0569, 0.9861, 0.7619],
        [0.4331, 0.4669, 0.2594, 0.5408],
        [0.5374, 0.0405, 0.2459, 0.3584]])
Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


In [4]:
# create a random tensor shape 7,7
tensor = torch.rand(7, 7)
tensor

tensor([[0.7629, 0.2841, 0.2318, 0.1209, 0.6854, 0.9740, 0.1189],
        [0.1673, 0.8073, 0.1532, 0.5379, 0.0883, 0.4336, 0.8177],
        [0.6906, 0.4142, 0.5444, 0.1488, 0.5148, 0.0420, 0.5604],
        [0.3870, 0.1663, 0.2191, 0.7025, 0.6664, 0.7923, 0.7866],
        [0.9287, 0.9138, 0.3662, 0.7167, 0.0050, 0.0458, 0.4835],
        [0.1643, 0.5882, 0.0206, 0.5634, 0.5603, 0.1279, 0.5735],
        [0.7333, 0.7385, 0.6158, 0.3436, 0.4410, 0.6128, 0.4116]])

In [5]:

tensor2 = torch.rand(1, 7)
mm = tensor.mm(tensor2.T)

In [8]:
torch.manual_seed(0)
tensor = torch.rand(7, 7)
tensor2 = torch.rand(1, 7)
mm = tensor.mm(tensor2.T)
mm

tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])